caddy:
    build: ./caddy
    volumes_from:
        - portfolio
    volumes:
        - ./caddy:/caddy
    ports:
        - 8042:8042
    links:
        - phpfpm

phpfpm:
    image: php:7.0-fpm
    expose:
        - "9000"
    volumes_from:
        - portfolio

portfolio:
    build: ./portfolio
    volumes:
        - ./portfolio:/var/www/html/portfolio/
    working_dir: /var/www/html/portfolio/