version: '3.7'
services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password
        ports:
          - 3306:3306
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    php:
        build:
          context: ./docker/php/local
          dockerfile: Dockerfile
        restart: on-failure
        user: ${LOCAL_USER}
        links:
          - mysql
        volumes:
            - './app/:/usr/src/app'
    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        depends_on:
            - php
        volumes:
            - './app/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
    yarn:
        build:
          context: .
          dockerfile: docker/yarn/Dockerfile
        user: ${LOCAL_USER}
        volumes:
            - './app/:/usr/src/app'