caddy:
    build: ./caddy
    volumes_from:
        - portfolio
    volumes:
        - ./caddy:/caddy
    ports:
        - 8078:8078
    links:
        - phpfpm

phpfpm:
    image: php:7.0-fpm
    expose:
        - "9000"
    volumes_from:
        - portfolio

portfolio:
    image: phusion/baseimage
    volumes:
        - ./portfolio:/var/www/html/portfolio